# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch\
$time\
$character
"""

# Inserts a blank line between shell prompts
add_newline = false

[os]
disabled = false
format = "[$symbol]($style) "
style = "fg:blue"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Fedora = "󰣛"
Amazon = ""
Android = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"

[directory]
truncation_length = 1
format = "[$path]($style) "

[time]
disabled = false
time_format = "%R"
utc_time_offset = "local"
format = "[$time](green) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
